export const LK_AUTH = "LK_AUTH"
export const LK_NO_AUTH = "LK_NO_AUTH"
export const SHOW_LOADER = "SHOW_LOADER"
export const HIDE_LOADER = "HIDE_LOADER"
export const SHOW_LOADER_CONTENT = "SHOW_LOADER_CONTENT"
export const HIDE_LOADER_CONTENT = "HIDE_LOADER_CONTENT"

export const LOAD_PANELS = "LOAD_PANELS"
export const LOAD_CONTENT = "LOAD_CONTENT"
export const DELETE_PANEL = "DELETE_PANEL"

export const LOAD_USERS = "LOAD_USERS"
export const SAVE_USER = "SAVE_USER"
export const CREATE_USER = "CREATE_USER"
export const DELETE_USER = "DELETE_USER"

// группы панелей
export const GET_LIST_GROUP_PANELS = "GET_LIST_GROUP_PANELS"
export const SHOW_LOADER_GROUPS = "SHOW_LOADER_GROUPS"
export const HIDE_LOADER_GROUPS = "HIDE_LOADER_GROUPS"

// панели состоящие и не состоящие в группах
export const GET_LIST_PANELS_IN_GROUP = "GET_LIST_PANELS_IN_GROUP"
export const GET_LIST_PANELS_NO_GROUP = "GET_LIST_PANELS_NO_GROUP"
export const SHOW_LOADER_PANELS_IN_GROUP = "SHOW_LOADER_PANELS_IN_GROUP"
export const HIDE_LOADER_PANELS_IN_GROUP = "HIDE_LOADER_PANELS_IN_GROUP"

// контент в группах
export const GET_CONTENT_IN_GROUP = "GET_CONTENT_IN_GROUP"
export const SHOW_LOADER_CONTENT_IN_GROUP = "SHOW_LOADER_CONTENT_IN_GROUP"
export const HIDE_LOADER_CONTENT_IN_GROUP = "HIDE_LOADER_CONTENT_IN_GROUP"