export const api_address = "http://193.124.58.144:4444"

export const auth = "/token"
export const role = "/api/getrole"
export const get_panels = "/panel/GetMyPanels"
export const get_dist = "/file/GetPlayer"
export const get_content = "/content/GetContent"
export const changePass = "/api/newpass"
export const post_file = "/content/AddFile"
export const delete_file = "/content/DeleteFile"
export const update_file = "/content/UpdateFile"
export const change_panels = "/panel/ChangePanel"
export const delete_panels = "/panel/deletePanel"