export const api_address = "http://193.124.58.144:4444"
//export const api_address = "http://localhost:52785"

export const auth = "/token"
export const role = "/api/getrole"
export const get_panels = "/panel/GetMyPanels"
export const get_dist = "/file/GetPlayer"
export const get_content = "/content/GetContent"
export const changePass = "/api/newpass"
export const post_file = "/content/AddFile"
export const delete_file = "/content/DeleteFile"
export const update_file = "/content/UpdateFile"
export const change_panels = "/panel/ChangePanel"
export const delete_panels = "/panel/deletePanel"
export const get_users = "/api/GetUsers"
export const save_user = "/api/change_user"
export const create_user = "/api/create_user"
export const delete_user = "/api/delete_user"
export const get_content_type = "/content/GetContentType"
export const getMyGroup = "/panel/getGroupPanels";
export const createGroup = "/panel/createGroup"
export const deleteGroup = "/panel/deleteGroup"
export const chanegNameCommentGroup = "/panel/change"
export const getPanelsInGroup = "/panel/getPanelsInGroup" // int user_id, int group_id
export const getPanelsNoGroup = "/panel/getPanelsNoGroup" // int user_id
export const setGroup = "/panel/setGroup" // int panel_id, int group_id
export const post_file_group = "/content/AddFileGroup"
export const getFileGroup = "/content/GetContentInGroup"
export const changeAutoDelete = "/content/ChangeTimeDelete"
export const deleteFileGroup = "/content/DeleteFileGroup"
export const getStatusFileInPanel = "/content/GetStatusFileInGroup" // получить статус файла загруженного в группу на панели 
export const changeMyData = "/api/ChangeMyData"
export const GetMyData = "/api/GetMyData"
export const changeOrient = "/panel/changeOrienatation"